parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    anddroid97.currency_converter:
        class: Anddroid97\CurrencyConverter\CurrencyConverter

    App\Services\CurrencyConverterService:
        arguments:
            - '@anddroid97.currency_converter'

    #Aliases
    Anddroid97\CurrencyConverter\CurrencyConverter: '@anddroid97.currency_converter'
